### ISSUE TITLE
[1.12.2] Right-click java.lang.NullPointerException

### ISSUE THREAD

**Issue by pimalel233** [MattJohns/BoneMealControl#1]
When right clicking randomly around me I start getting errors:
https://paste.dimdev.org/ejokejasaw.mccrash

[BoneMealControl.txt](https://github.com/MattJohns/BoneMealControl/files/4080182/BoneMealControl.txt)

BoneMealControl-1.3
Forge 14.23.5.2838
VanillaFix 1.0.10-99 (mostly to get notified about the error when it happens)

Also attached my config.

**Comment by MattJohns** [comment]
Thanks for taking the time to report that one.

I managed to reproduce it and it's fixed in 1.4 .
